#!/bin/sh
case $0 in
	*mkdeck)
		decksh enrollment.dsh |  pdf       -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
	*mkdeck-png)
		decksh enrollment.dsh  | pngdeck   -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
esac
