#!/bin/sh
case $0 in
	*mkdeck)
		decksh crime.dsh | pdfdeck -stdout -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* - > f.pdf ;;
	*mkdeck-png)
		decksh crime.dsh | pngdeck -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* /dev/stdin ;;
esac
