#!/bin/sh
case $0 in
	*mkdeck)
		decksh church.dsh | pdf -pagesize $portrait -sans PublicSans-BoldItalic -serif Charter-Regular $* ;;
	*mkdeck-png)
		decksh church.dsh | pngdeck -pagesize $portrait -sans PublicSans-BoldItalic -serif Charter-Regular $* /dev/stdin ;;
esac
