#!/bin/sh
case $0 in
	*mkdeck)
		decksh religion.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif Charter-Regular $* ;;
	*mkdeck-png)
		decksh religion.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif Charter-Regular $* /dev/stdin ;;
esac
