plate01/mkdeck:		decksh georgia-negro.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Regular $* ;;
plate01/mkdeck:		decksh georgia-negro.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Regular $* /dev/stdin ;;
plate02/mkdeck:		decksh uspop.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* ;;
plate02/mkdeck:		decksh uspop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin ;;
plate03/mkdeck:		decksh statepop.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* ;;
plate03/mkdeck:		decksh statepop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin ;;
plate04/mkdeck:		decksh georgia-pop.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate04/mkdeck:		decksh georgia-pop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate05/mkdeck:# (cat annotations.dsh plate05poly.dsh close.dsh ) | decksh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait
plate05/mkdeck:		decksh gapop.dsh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait ;;
plate05/mkdeck:		decksh gapop.dsh | pngdeck -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait $* /dev/stdin ;;
plate06/mkdeck:		decksh gapop2.dsh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait $* ;;
plate06/mkdeck:		decksh gapop2.dsh | pngdeck -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait $* /dev/stdin ;;
plate07/mkdeck:		decksh wc.dsh | pdf -pagesize $portrait -sans PublicSans-Bold  -serif PublicSans-Regular $* ;;
plate07/mkdeck:		decksh wc.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold  -serif PublicSans-Regular $* /dev/stdin ;;
plate09/mkdeck:		decksh agedist.dsh | pdf -pagesize $portrait -sans PublicSans-Bold  -serif PublicSans-Regular $* ;;
plate09/mkdeck:		decksh agedist.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold  -serif PublicSans-Regular $* /dev/stdin ;;
plate10/mkdeck:		decksh conjugal.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* ;;
plate10/mkdeck:		decksh conjugal.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin ;;
plate13/mkdeck:		decksh color.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Medium  $* ;;
plate13/mkdeck:		decksh color.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Medium  $* /dev/stdin ;;
plate14/mkdeck:		decksh illiteracy.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* ;;
plate14/mkdeck:		decksh illiteracy.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin ;;
plate15/mkdeck:		decksh children.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* ;;
plate15/mkdeck:		decksh children.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin ;;
plate16/mkdeck:		decksh teachers.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Regular $* ;;
plate16/mkdeck:		decksh teachers.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Regular $* /dev/stdin ;;
plate17/mkdeck:		decksh students.dsh | pdfdeck -stdout -pagesize $portrait -serif PublicSans-Bold -sans PublicSans-Regular $* /dev/stdin > f.pdf ;;
plate17/mkdeck:		decksh students.dsh | pngdeck         -pagesize $portrait -serif PublicSans-Bold -sans PublicSans-Regular $* /dev/stdin ;;
plate18/mkdeck:		decksh land.dsh | pdfdeck -stdout -pagesize $portrait -serif PublicSans-Bold -sans Charter-Regular $* /dev/stdin > f.pdf ;;
plate18/mkdeck:		decksh land.dsh | pngdeck         -pagesize $portrait -serif PublicSans-Bold -sans Charter-Regular $* /dev/stdin ;;
plate19/mkdeck:		decksh land.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate19/mkdeck:		decksh land.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate20/mkdeck:# (cat annotations.dsh; ./mkplate20; cat close.dsh ) | decksh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait
plate20/mkdeck:		decksh galand.dsh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait $* ;;
plate20/mkdeck:		decksh galand.dsh | pngdeck -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait $* /dev/stdin ;;
plate30/mkdeck:		decksh tenant.dsh | pdf -pagesize $landscape -sans PublicSans-Regular $* ;;
plate30/mkdeck:		decksh tenant.dsh | pngdeck -pagesize $landscape -sans PublicSans-Regular $* /dev/stdin ;;
plate31/mkdeck:decksh income.dsh | pdf -pagesize 2016,1584 -sans PublicSans-Bold -serif PublicSans-Thin  $*
plate37/mkdeck:		decksh overview.dsh | pdf -pagesize $portrait -sans PublicSans-Thin -serif PublicSans-Bold $* ;;
plate37/mkdeck:		decksh overview.dsh | pngdeck -pagesize $portrait -sans PublicSans-Thin -serif PublicSans-Bold $* /dev/stdin ;;
plate38/mkdeck:		decksh dist.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* ;;
plate38/mkdeck:		decksh dist.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin ;;
plate39/mkdeck:		decksh population.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate39/mkdeck:		decksh population.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate40/mkdeck:		decksh popcompare.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
plate40/mkdeck:		decksh popcompare.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
plate41/mkdeck:		decksh countries-pop.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate41/mkdeck:		decksh countries-pop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate42/mkdeck:		decksh population-proportion.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate42/mkdeck:		decksh population-proportion.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate43/mkdeck:		decksh occupation.dsh | pdf     -pagesize $portrait -sans PublicSans-Medium -serif Charter-Regular $* ;;
plate43/mkdeck:		decksh occupation.dsh | pngdeck -pagesize $portrait -sans PublicSans-Medium -serif Charter-Regular $* /dev/stdin ;;
plate47/mkdeck:		decksh natill.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
plate47/mkdeck:		decksh natill.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
plate50/mkdeck:		decksh generation.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Regular $* ;;
plate50/mkdeck:		decksh generation.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif PublicSans-Regular $* /dev/stdin ;;
plate51/mkdeck:		decksh free-slave.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate51/mkdeck:		decksh free-slave.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate52/mkdeck:		decksh ur.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
plate52/mkdeck:		decksh ur.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
plate53/mkdeck:		decksh conjugal.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
plate53/mkdeck:		decksh conjugal.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
plate54/mkdeck:		decksh pop.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
plate54/mkdeck:		decksh pop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
plate55/mkdeck:		decksh property.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
plate55/mkdeck:		decksh property.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
plate56/mkdeck:		decksh land.dsh | pdf -pagesize $portrait -sans PublicSans-Regular $* ;;
plate56/mkdeck:		decksh land.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular $* /dev/stdin ;;
plate57/mkdeck:		decksh business.dsh | pdf -pagesize $portrait -sans PublicSans-Regular $*
plate57/mkdeck:		decksh business.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular $* /dev/stdin
plate58/mkdeck:		decksh pauper.dsh | pdf  -author "Anthony Starks" -title "Pauperism Among American Negroes"   -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* ;;
plate58/mkdeck:		decksh pauper.dsh | pngdeck -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* /dev/stdin ;;
plate59/mkdeck:		decksh mortality.dsh | pdf -pagesize $portrait $* ;;
plate59/mkdeck:		decksh mortality.dsh | pngdeck -pagesize $portrait $* /dev/stdin ;;
plate60/mkdeck:		decksh crime.dsh | pdfdeck -stdout -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* /dev/stdin > f.pdf ;;
plate60/mkdeck:		decksh crime.dsh | pngdeck -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* /dev/stdin ;;
plate61/mkdeck:		decksh news.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif Charter-Regular $* ;;
plate61/mkdeck:		decksh news.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif Charter-Regular $* /dev/stdin ;;
platexx/mkdeck:		decksh illiteracy.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
platexx/mkdeck:		decksh illiteracy.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
