#!/bin/sh
export portrait=1584,2016
export landscape=2016,1584

decksh title.dsh | pdfdeck -stdout -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular - > title.pdf
ls plate*/f1.png | ./catalog9 | decksh | pdfdeck -stdout -pagesize $portrait - > toc.pdf

for i in plate*
do
	cd $i
	echo $i
	./mkdeck
	cd ..
done
mutool merge  -o data-portraits.pdf title.pdf toc.pdf plate*/f.pdf 