#!/bin/sh
decksh title.dsh | pdfdeck -stdout -pagesize 1100,1400 -sans PublicSans-Regular - > title.pdf
for i in plate*
do
	cd $i
	./mkdeck
	cd ..
done
pdfunite title.pdf plate*/f.pdf data-portraits.pdf
