#!/bin/sh
export portrait=1584,2016
export landscape=2016,1584
decksh title.dsh | pdfdeck -author "Anthony Starks" -title "Recreations of DuBois Data Stories" -stdout -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular - > title.pdf
for i in plate*
do
	cd $i
	echo $i
	./mkdeck
	cd ..
done
pdfunite title.pdf plate*/f.pdf data-portraits.pdf
