#!/bin/sh
case $0 in
	*mkdeck)
		decksh agedist.dsh | pdf -pagesize $portrait -sans PublicSans-Bold  -serif PublicSans-Regular $* ;;
	*mkdeck-png)
		decksh agedist.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold  -serif PublicSans-Regular $* /dev/stdin ;;
esac
