#!/bin/sh
case $0 in
	*mkdeck)
		decksh popcompare.dsh | pdf -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* ;;
	*mkdeck-png)
		decksh popcompare.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold -serif Charter-Regular $* /dev/stdin ;;
esac
