#!/bin/sh
(
echo 'deck
slide
ctext "LAND OWNED BY NEGROES IN GEORGIA, U.S.A  1870-1900" 50 95 3 "serif"
clist 70 75 1.3 "sans" "gray" 100 1.6
li "THE FIGURES INDICATE THE NUMBER OF"
li "ACRES OWNED IN EACH COUNTY IN 1899"
elist'
./mkall
echo 'eslide
edeck'
) | decksh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait