#!/bin/sh
# (cat annotations.dsh; ./mkall; cat close.dsh ) | decksh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait
decksh galand.dsh | pdf -sans PublicSans-Regular -serif PublicSans-Bold -pagesize $portrait