#!/bin/sh
decksh module.dsh|
pdfdeck -title "Using Du Bois Visualizations in STEM Education" -author "Anthony Starks" -sans PublicSans-SemiBold -serif Charter-Regular -mono Inconsolata-Bold -stdout -grid $deckgrid  - > dubois-module.pdf
