#!/bin/sh
case $0 in
	*mkdeck)
		decksh pauper.dsh | pdf  -author "Anthony Starks" -title "Pauperism Among American Negroes"   -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* ;;
	*mkdeck-png)
		decksh pauper.dsh | pngdeck -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* /dev/stdin ;;
esac
