#!/bin/sh
case $0 in
	*mkdeck)
		decksh pauper.dsh | pdf      -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* ;;
	*mkdeck-png)
		decksh pauper.dsh | pngdeck -pagesize $portrait -serif Charter-Regular -sans PublicSans-Regular $* /dev/stdin ;;
esac
