#!/bin/sh
# awk '{printf "mkpoly 5 70 20 60 -2361.58 881.14 -1347.71 1323.91 \"\" \"%s\" ../plate02/a-%s.d\n", $2, $1}' dist.d | sh > allstates.dsh
decksh dist.dsh | pdf -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $*
