#!/bin/sh
case $0 in
	*mkdeck)
		decksh students.dsh | pdfdeck -stdout -pagesize $portrait -serif PublicSans-Bold -sans PublicSans-Regular $* /dev/stdin > f.pdf ;;
	*mkdeck-png)
		decksh students.dsh | pngdeck         -pagesize $portrait -serif PublicSans-Bold -sans PublicSans-Regular $* /dev/stdin ;;
esac
