#!/bin/sh
awk -F$'\t' '
{
		name=substr($1,1,3)
		value=$NF
		split($1, names," ")
		printf "\n// %s\n", $1
		printf "%s=vmap %s dmin dmax smin smax\n", name, value
		printf "clist labelx labely ls \"sans\" labelcolor 100 1.2\n"
		for (i=1; i <= length(names); i++) {
			printf "  li \"%s\"\n", names[i]
		}
		printf "elist\n"
		printf "hline bx by %s bw bcolor\n", name
		printf "etext \"%'"'"'d\" lx ly ls\n", value
		printf "by-=bskip\n"
		printf "ly-=bskip\n"
		printf "labely-=bskip\n"
}' $*