#!/bin/sh
#awk -F$'\t' '{printf "mkpoly 15 90 30 65 66.95 124.78 24.27 49.34 \"\" \"%s\" %s.d\n", $2, $1}' popcolor.csv | sh > allstates.dsh
decksh uspop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Regular -serif PublicSans-Bold $* /dev/stdin
