#!/bin/sh
case $0 in
	*mkdeck)
		decksh land.dsh | pdfdeck -stdout -pagesize $portrait -serif PublicSans-Bold -sans Charter-Regular $* /dev/stdin > f.pdf ;;
	*mkdeck-png)
		decksh land.dsh | pngdeck         -pagesize $portrait -serif PublicSans-Bold -sans Charter-Regular $* /dev/stdin ;;
esac
