#!/bin/sh
case $0 in
	*mkdeck)
		decksh georgia-pop.dsh | pdf -pagesize $portrait -sans PublicSans-Bold $* ;;
	*mkdeck-png)
		decksh georgia-pop.dsh | pngdeck -pagesize $portrait -sans PublicSans-Bold $* /dev/stdin ;;
esac
