#!/bin/sh
case $0 in
	*mkdeck)
		decksh occupation.dsh | pdf     -pagesize $portrait -sans PublicSans-Medium -serif Charter-Regular $* ;;
	*mkdeck-png)
		decksh occupation.dsh | pngdeck -pagesize $portrait -sans PublicSans-Medium -serif Charter-Regular $* /dev/stdin ;;
esac

