#!/bin/sh
case $0 in
	*mkdeck)
		decksh overview.dsh | pdf -pagesize $portrait -sans PublicSans-Thin -serif PublicSans-Bold $* ;;
	*mkdeck-png)
		decksh overview.dsh | pngdeck -pagesize $portrait -sans PublicSans-Thin -serif PublicSans-Bold $* /dev/stdin ;;
esac
